### PR TITLE
Some tutorials links added.

### PR DESCRIPTION
**Pull request by DiegoFLM**
I added links for GeeksforGeeks tutorials.

### CODE REVIEW

**Comment by JuanCamilo-R** [comment]
Sigue así, Diego!

**Comment by DavidHernandezUV** [comment]
Great idea

**Comment by jennyferbm13** [comment]
very good

**Comment by andresfeliper3** [comment]
The tutorial links are ok

**Comment by DiegoFLM** [comment]
Thankyou!

**Pull request merged**
